### ISSUE TITLE
not working with roots 4.0.1

### ISSUE THREAD

**Issue by NathanWalker** [samccone/infestor#17]
I've tried a million different ways and run into this error everytime:

```
/usr/local/Cellar/node/5.5.0/lib/node_modules/roots/node_modules/infestor/index.js:86
        opts.injectContent.apply(this, [content, writeEncoding].concat([].slice.call(arguments, 0))),
                          ^

TypeError: Cannot read property 'apply' of undefined
  at ServerResponse.res.end (/usr/local/Cellar/node/5.5.0/lib/node_modules/roots/node_modules/infestor/index.js:86:27)
  at ReadStream.onend (_stream_readable.js:491:10)
  at ReadStream.g (events.js:273:16)
  at emitNone (events.js:85:20)
  at ReadStream.emit (events.js:179:7)
  at endReadableNT (_stream_readable.js:906:12)
  at nextTickCallbackWith2Args (node.js:474:9)
  at process._tickCallback (node.js:388:17)
```

I opened that `index.js` and put console statements throughout and it's very troubling. The `opts` object never sets the `injectContent` despite what is happening here:
https://github.com/samccone/infestor/blob/master/index.js#L6

:(

**Comment by NathanWalker** [comment]
Ok nvm, it's something with `charge` config.

**Comment by jescalan** [comment]
Neither charge nor infestor are dependencies for roots `4.x`. Roots 4 uses browsersync as the dev server...
